# OAuth configuration for HTPasswd authentication
# configs/oauth-htpasswd.yaml

apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: htpasswd_provider
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpasswd-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: htpasswd-secret
  namespace: openshift-config
type: Opaque
data:
  # This is htpasswd -nb -B -b admin password
  # Replace with your own htpasswd generated string in base64
  htpasswd: YWRtaW46JDJ5JDA1JHltRFQ3YTVYaS9MTEptV1h5a0JLQWVoOGVSZzJXNDFRdkp1NzVIYmF1V2xGNkU1bC52TVdD
